on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n azCR01 -g azCR019123-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n azCR01 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n azCR01 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n azCR01 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: azcr01.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t azcr01.azurecr.io/k8scluster:${{ github.sha }}
        docker push azcr01.azurecr.io/k8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_k8scluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8scluster2563 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8scluster2563`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8scluster2563
        container-registry-url: azcr01.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: k8sclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: k8scluster2563
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azcr01.azurecr.io/k8scluster:${{ github.sha }}
        imagepullsecrets: |
          k8sclusterdockerauth